### Server 配置 ##########
server:
  port: 9080
### Spring 配置 ##########
spring:
  cache:
    type: redis
  redis:
    database: 5
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3600
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  # 驱动配置信息 ###
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/neilrenv4?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 1
    minIdle: 1
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT1FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
    logSlowSql: true
    #### elasticsearch ##########
    elasticsearch:
      jest:
        uris:
        - http://localhost:9200
        read-timeout: 5000
  aop:
    auto: true
### NeilRen 配置 ##########
neilren:
  version: 1.0
  host: https://www.neilren.com
  googletotpseed:
  googletotpissuer: NEILREN.COM
  pagecss:
  - https://cdn.neilren.com/NeilRenV4/css/bootstrap.min.css
  - https://cdn.neilren.com/NeilRenV4/syntaxhighlighter/styles/shCore.css
  - https://cdn.neilren.com/NeilRenV4/syntaxhighlighter/styles/shThemeDefault.css
  - https://cdn.neilren.com/NeilRenV4/css/neilren4j.css
  pagejss:
  - https://cdn.neilren.com/NeilRenV4/js/jquery-3.3.1.min.js
  - https://cdn.neilren.com/NeilRenV4/js/popper-1.14.3.js
  - https://cdn.neilren.com/NeilRenV4/js/bootstrap.min.js
  - https://cdn.neilren.com/NeilRenV4/js/hashes.js
  - https://cdn.neilren.com/NeilRenV4/js/neilren4j.js
  - https://cdn.neilren.com/NeilRenV4/syntaxhighlighter/scripts/shCore.js
  - https://cdn.neilren.com/NeilRenV4/syntaxhighlighter/scripts/shAutoloader.js
  - //msite.baidu.com/sdk/c.js?appid=1606398243645928
  - //qzonestyle.gtimg.cn/qzone/v6/portal/gy/404/data.js
  # - https://www.googletagmanager.com/gtag/js?id=UA-45593016-2
  baidu:
    site: https://www.neilren.com/
    token:
    xiongzhangappid:
    xiongzhangtoken:
  aliyun:
    accesskey:
    secret:
    openSearch:
      appname: NEILREN
      host: http://vpc.opensearch-cn-beijing.aliyuncs.com
    oss:
      #oss-cn-beijing.aliyuncs.com
      endpoint: http://oss-cn-beijing-internal.aliyuncs.com
      bucketname: bj-neilren
      rootPath: neilren4j/upload/
    cdn:
      host: https://cdn.neilren.com/
    apiappcodeip:
  email:
    smtp: smtp.mxhichina.com
    port: 465
    debug: true
    from: no-reply@neilren.com
    ssl: true
    username: no-reply@neilren.com
    password:
### MyBatis 配置 ##########
mybatis:
  mapper-locations: classpath:mapper/mysql/*.xml
### PageHelper 配置 ##########
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql